name: week_1
description: "A new Flutter project."

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.5
  get: ^4.6.5

flutter:

  uses-material-design: true
